version: '3.8'

services:
  app:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/assessment
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: assessment
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql