name: CI Workflow
on:
  push:
    branches: [ main, WRD_T1 ]

jobs:
  unit-test:
    name: Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./posttest

    steps:
      -   name: Checkout Code
          uses: actions/checkout@v3
      -   name: Setup Java17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'zulu'
      -   name: Run Unit Tests
          run: ./gradlew test